import { chromium, expect } from 'playwright/test'
import { mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { tmpdir } from 'node:os'
import { createRequire } from 'node:module'

const root = resolve(import.meta.dir, '..')
const require = createRequire(join(root, 'package.json'))
const stage = mkdtempSync(join(tmpdir(), 'projects-detail-browser-'))
const report = join(root, 'test-results/bakin-ui-detail-interactions')
const errors: string[] = []
const checks: string[] = []
const result = await Bun.build({ entrypoints: [join(root, 'tests/detail.fixture.tsx')], outdir: stage, target: 'browser', format: 'esm', splitting: true,
  naming: { entry: 'fixture.[ext]', chunk: '[name]-[hash].[ext]' }, define: { 'process.env.NODE_ENV': JSON.stringify('production') },
  plugins: [{ name: 'canonical-css', setup(builder) { builder.onResolve({ filter: /^@makinbakin\/sdk\/styles\.css$/ }, () => ({ path: 'styles', namespace: 'canonical-css' })); builder.onLoad({ filter: /.*/, namespace: 'canonical-css' }, () => ({ contents: '', loader: 'css' })) } }],
})
if (!result.success) throw new Error(result.logs.map(String).join('\n'))
await Bun.write(join(stage, 'sdk-styles.css'), readFileSync(require.resolve('@makinbakin/sdk/styles.css')))
await Bun.write(join(stage, 'index.html'), '<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/sdk-styles.css"></head><body><div id="root"></div><script type="module" src="/fixture.js"></script></body></html>')
const server = Bun.serve({ hostname: '127.0.0.1', port: 0, async fetch(request) {
  const path = new URL(request.url).pathname
  const file = Bun.file(join(stage, path === '/' ? 'index.html' : path))
  return await file.exists() ? new Response(file) : new Response('Not found', { status: 404 })
} })
const browser = await chromium.launch()
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
  page.setDefaultTimeout(15_000)
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto(server.url.href)
  await page.locator('[data-md-changed-block]').waitFor()
  const composer = page.getByRole('textbox', { name: 'Ask about this project...' })
  await composer.fill('Do not send this draft')
  await page.getByRole('textbox', { name: 'Add task', exact: true }).fill('Retained task draft')
  const composerNode = await composer.elementHandle()
  await page.getByRole('button', { name: 'Edit', exact: true }).click()
  await expect(page.getByRole('form', { name: 'Edit project' })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Add task', exact: true })).toHaveValue('Retained task draft')
  await expect(composer).toHaveValue('Do not send this draft')
  expect(await composerNode!.evaluate(node => node.isConnected)).toBe(true)
  await page.getByRole('button', { name: 'Done editing' }).click()
  await expect(page.getByRole('form', { name: 'Edit project' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Edit', exact: true }).click()
  console.log('Checking staged title after read/edit transitions')
  await page.getByRole('textbox', { name: 'Project title', exact: true }).fill('My staged title')
  await page.evaluate(() => { const fixture = (window as any).__projectsFixture; fixture.state.project.title = 'Agent changed title'; fixture.state.project.owner = 'agent'; fixture.changed() })
  await expect(page.getByRole('button', { name: 'Keep my title' })).toBeVisible()
  await expect(page.getByRole('textbox', { name: 'Project title', exact: true })).toHaveValue('My staged title')
  await page.getByRole('button', { name: 'Keep my title' }).click()
  await page.getByRole('button', { name: 'Save changes', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1, name: 'My staged title' })).toBeVisible()
  expect(await page.evaluate(() => (window as any).__projectsFixture.state.requests.filter((request: any) => request.method === 'PUT' && request.path.endsWith('/sample')).at(-1).body)).toEqual({ title: 'My staged title', expected: { title: 'Agent changed title' } })
  checks.push('read/edit keeps checklist and composer mounted; overlapping agent updates require reviewed expected values')

  await page.evaluate(() => { (window as any).__projectsFixture.state.loseAddReply = true })
  await page.getByRole('button', { name: 'Add task to checklist' }).click()
  await expect(page.getByText('Could not reach Projects. Check your connection and retry.')).toBeVisible()
  await page.getByRole('button', { name: 'Add task to checklist' }).click()
  await expect(page.getByRole('textbox', { name: 'Add task', exact: true })).toHaveValue('')
  expect(await page.evaluate(() => (window as any).__projectsFixture.state.project.tasks.filter((item: any) => item.title === 'Retained task draft').length)).toBe(1)
  checks.push('lost add response retains the input and retries one receipt without a duplicate')

  await page.getByRole('textbox', { name: 'Project title', exact: true }).fill('Saved before partial failure')
  for (const [title, value] of [['Prepare camera gear', 'First saved description'], ['Confirm walking route', 'Second saved description']]) {
    await page.getByRole('button', { name: title, exact: true }).click()
    await page.getByRole('button', { name: `Edit details for ${title}` }).click()
    await page.getByRole('textbox', { name: `Details for ${title}` }).fill(value!)
  }
  await page.getByRole('textbox', { name: 'Add task', exact: true }).fill('Added after descriptions')
  await page.evaluate(() => { (window as any).__projectsFixture.state.failures['PUT /api/plugins/projects/sample/checklist/t002'] = 1 })
  await page.getByRole('button', { name: 'Back to projects' }).click()
  await page.getByRole('button', { name: 'Save all and leave' }).click()
  await expect(page.getByText('Project changes are saved. Some checklist edits remain unsaved; retry saves only the unfinished work.')).toBeVisible()
  await page.getByRole('button', { name: 'Save all and leave' }).click()
  await expect(page.getByRole('heading', { name: 'Project list fixture' })).toBeVisible()
  const requests = await page.evaluate(() => (window as any).__projectsFixture.state.requests)
  expect(requests.filter((request: any) => request.method === 'PUT' && request.path.endsWith('/checklist/t001'))).toHaveLength(1)
  expect(requests.filter((request: any) => request.method === 'PUT' && request.path.endsWith('/checklist/t002'))).toHaveLength(2)
  expect(requests.filter((request: any) => request.path.endsWith('/ask'))).toHaveLength(0)
  checks.push('Save All retains partial successes, retries only pending drafts, then exits without sending the composer')
  await page.close()

  const mobile = await browser.newPage({ viewport: { width: 320, height: 800 } })
  mobile.setDefaultTimeout(15_000)
  mobile.on('pageerror', error => errors.push(error.message))
  mobile.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await mobile.goto(server.url.href)
  await mobile.locator('[data-md-changed-block]').waitFor()
  const disclosure = mobile.getByRole('button', { name: /^Brainstorm/ })
  await expect(disclosure).toHaveAttribute('aria-expanded', 'false')
  await disclosure.click()
  const mobileComposer = mobile.getByRole('textbox', { name: 'Ask about this project...' })
  await mobileComposer.fill('Mobile draft remains')
  const mounted = await mobileComposer.elementHandle()
  await disclosure.click()
  await expect(mobileComposer).toBeHidden()
  expect(await mounted!.evaluate(node => node.isConnected)).toBe(true)
  await disclosure.click()
  await expect(mobileComposer).toHaveValue('Mobile draft remains')
  await mobile.reload()
  await expect(mobile.getByRole('button', { name: /^Brainstorm/ })).toHaveAttribute('aria-expanded', 'true')
  await expect(mobile.getByRole('textbox', { name: 'Ask about this project...' })).toHaveValue('Mobile draft remains')
  await mobile.evaluate(() => { document.documentElement.style.fontSize = '200%' })
  expect(await mobile.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1)).toBe(true)
  await mobile.screenshot({ path: join(report, 'mobile-draft-200.png'), fullPage: true })
  checks.push('empty mobile brainstorm collapses; toggling keeps its DOM/draft; reload restores it expanded; 200% text fits')
  await mobile.goto(`${server.url.href}?scenario=conversation`)
  await expect(mobile.getByRole('button', { name: /^Brainstorm/ })).toHaveAttribute('aria-expanded', 'true')
  const historyRegion = mobile.getByRole('region', { name: 'Project brainstorm history' })
  await expect(historyRegion).toBeVisible()
  await historyRegion.evaluate(element => { element.scrollTop = 100 })
  const scrollTop = await historyRegion.evaluate(element => element.scrollTop)
  expect(scrollTop).toBeGreaterThan(0)
  await mobile.getByRole('button', { name: /^Brainstorm/ }).click()
  await mobile.getByRole('button', { name: /^Brainstorm/ }).click()
  expect(await historyRegion.evaluate(element => element.scrollTop)).toBe(scrollTop)
  checks.push('mobile conversation history opens automatically and retains its scroll position through disclosure')

  await mobile.goto(server.url.href)
  const hideCompleted = mobile.getByRole('switch', { name: 'Hide completed (1)' })
  await expect(mobile.getByRole('button', { name: 'Prepare camera gear', exact: true })).toBeVisible()
  await hideCompleted.click()
  await expect(mobile.getByRole('button', { name: 'Prepare camera gear', exact: true })).toHaveCount(0)
  await expect(mobile.getByText('1 of 2 tasks completed', { exact: true })).toBeVisible()
  await mobile.reload()
  await expect(mobile.getByRole('switch', { name: 'Hide completed (1)' })).toBeChecked()
  await mobile.getByRole('switch', { name: 'Hide completed (1)' }).click()
  await mobile.getByRole('textbox', { name: 'Add task', exact: true }).fill('Discard only this checklist draft')
  const mobileDraft = mobile.getByRole('textbox', { name: 'Ask about this project...' })
  await mobileDraft.fill('Composer stays private')
  expect(await mobile.evaluate(() => !window.dispatchEvent(new Event('beforeunload', { cancelable: true })))).toBe(true)
  await mobile.getByRole('button', { name: 'Back to projects' }).click()
  await mobile.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(mobile.getByRole('textbox', { name: 'Add task', exact: true })).toHaveValue('Discard only this checklist draft')
  await mobile.getByRole('button', { name: 'Back to projects' }).click()
  await mobile.getByRole('button', { name: 'Discard changes', exact: true }).click()
  await expect(mobile.getByRole('heading', { name: 'Project list fixture' })).toBeVisible()
  expect(await mobile.evaluate(() => (window as any).__projectsFixture.state.requests.filter((request: any) => request.method !== 'GET' && !request.path.endsWith('/brainstorm/seen')))).toEqual([])
  checks.push('completed preference persists with truthful counts; unload/Stay protect drafts; Discard exits without writes')
  await mobile.goto(server.url.href)
  await mobile.getByRole('textbox', { name: 'Add task', exact: true }).fill('Removed during retry')
  await mobile.evaluate(() => { (window as any).__projectsFixture.state.loseAddReply = true })
  await mobile.getByRole('button', { name: 'Add task to checklist' }).click()
  await expect(mobile.getByText('Could not reach Projects. Check your connection and retry.')).toBeVisible()
  await mobile.evaluate(() => {
    const fixture = (window as any).__projectsFixture
    fixture.state.project.tasks = fixture.state.project.tasks.filter((item: any) => item.title !== 'Removed during retry')
    fixture.changed()
  })
  await mobile.getByRole('button', { name: 'Back to projects' }).click()
  await mobile.getByRole('button', { name: 'Save all and leave' }).click()
  await expect(mobile.getByText('Project changes are saved. Some checklist edits remain unsaved; retry saves only the unfinished work.')).toBeVisible()
  await mobile.getByRole('button', { name: 'Cancel', exact: true }).click()
  await expect(mobile.getByRole('textbox', { name: 'Add task', exact: true })).toHaveValue('Removed during retry')
  await expect(mobile.getByRole('button', { name: 'Add task to checklist' })).toBeDisabled()
  await mobile.getByRole('button', { name: 'Discard removed task draft' }).click()
  await expect(mobile.getByRole('textbox', { name: 'Add task', exact: true })).toHaveValue('')
  expect(await mobile.evaluate(() => window.dispatchEvent(new Event('beforeunload', { cancelable: true })))).toBe(true)
  checks.push('deleted add replay blocks Save All and remains a protected draft until explicitly discarded')
  await mobile.goto(`${server.url.href}?scenario=history-error`)
  await expect(mobile.getByText('Plan history unavailable')).toBeVisible()
  await expect(mobile.getByText('No plan versions yet')).toHaveCount(0)
  await mobile.getByRole('button', { name: 'Try again', exact: true }).click()
  await mobile.locator('[data-md-changed-block]').waitFor()
  checks.push('history failure is retryable and never presented as empty')
  expect(errors).toEqual([])
  await Bun.write(join(report, 'report.json'), JSON.stringify({ status: 'passed', checks, errors }, null, 2))
  await Bun.write(join(report, 'index.html'), `<!doctype html><title>Projects detail interactions</title><h1>Projects detail interactions passed</h1><ul>${checks.map(check => `<li>${check}</li>`).join('')}</ul><img src="mobile-draft-200.png" alt="Mobile brainstorm draft at 200% text">`)
  console.log(`Passed ${checks.length} Projects detail browser scenarios. Report: ${report}/index.html`)
} catch (error) {
  for (const context of browser.contexts()) for (const page of context.pages()) {
    await page.screenshot({ path: join(report, 'failure.png'), fullPage: true }).catch(() => {})
    await Bun.write(join(report, 'failure.html'), await page.content())
  }
  console.error('Browser console:', errors)
  throw error
} finally { await browser.close(); server.stop(true); rmSync(stage, { recursive: true, force: true }) }
