import React from 'react'

function createElement(tag, defaultProps = {}) {
  return function Component({ children, ...props }) {
    return React.createElement(tag, { ...defaultProps, ...props }, children)
  }
}

export const Alert = createElement('div')
export const Avatar = createElement('span')
export const Badge = createElement('span', { 'data-testid': 'badge' })
export const Button = createElement('button')
export const Card = createElement('div')
export const Checkbox = createElement('input', { type: 'checkbox' })
export const Collapsible = createElement('div')
export const Command = createElement('div')
export const Dialog = ({ children, open = true }) => open ? React.createElement('div', null, children) : null
export const DialogContent = createElement('div')
export const DialogHeader = createElement('div')
export const DialogTitle = createElement('h2')
export const DropdownMenu = createElement('div')
export const DropdownMenuTrigger = createElement('button')
export const DropdownMenuContent = createElement('div')
export const DropdownMenuItem = createElement('button')
export const DropdownMenuSeparator = createElement('hr')
export const Form = createElement('form')
export const Input = createElement('input')
export const InputGroup = createElement('div')
export const Label = createElement('label')
export const Popover = createElement('div')
export const Progress = createElement('progress')
export const Select = ({ children }) => React.createElement('div', null, children)
export const SelectContent = createElement('div')
export const SelectItem = createElement('button')
export const SelectTrigger = createElement('button')
export const SelectValue = ({ children }) => React.createElement('span', null, children)
export const Separator = createElement('hr')
export const Sheet = createElement('div')
export const Skeleton = createElement('div')
export const Switch = createElement('button')
export const Table = createElement('table')
export const TableHeader = createElement('thead')
export const TableBody = createElement('tbody')
export const TableRow = createElement('tr')
export const TableHead = createElement('th')
export const TableCell = createElement('td')
export const Tabs = createElement('div')
export const Textarea = createElement('textarea')
export const Tooltip = createElement('span')
